server:
  port: 8082
spring:
  mvc:
    servlet:
      path: /web
  application:
    name: web
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public