server:
  port: 8081
spring:
  mvc:
    servlet:
      path: /admin
  application:
    name: admin
    cloud:
      nacos:
        server-addr: 127.0.0.1:8848
        discovery:
          username: nacos
          password: nacos
          namespace: public